DB_PASSWORD = "@Percata23"
SUPABASE_URL = "https://xkwusqpqmtjfehabofiv.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhrd3VzcXBxbXRqZmVoYWJvZml2Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0Mzc0NjA1NSwiZXhwIjoyMDU5MzIyMDU1fQ.Z2Zzwt6lKCoaB9xPh-3lK3e-hm9Sq0wpKxh1qW-Sh20"
